[36m[2023-04-09 23:05:31 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:05:31 DEBUG] [cli:115][39m Running command 'init'
[36m[2023-04-09 23:05:31 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:05:32 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[36m[2023-04-09 23:06:20 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:06:20 DEBUG] [cli:115][39m Running command 'init'
[36m[2023-04-09 23:06:20 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:06:20 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[36m[2023-04-09 23:06:37 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:06:37 DEBUG] [cli:115][39m Running command 'init'
[36m[2023-04-09 23:06:37 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:06:38 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[36m[2023-04-09 23:09:28 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:09:28 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:09:28 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:09:29 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:09:29 INFO] [package:22][39m Attempting to download and install package 'chaosspring.actions'
[36m[2023-04-09 23:09:33 DEBUG] [package:32][39m 
[36m[2023-04-09 23:09:33 DEBUG] [package:36][39m failed to install `chaosspring.actions`
    =================
    
    =================
    ERROR: Could not find a version that satisfies the requirement chaosspring.actions (from versions: none)
    ERROR: No matching distribution found for chaosspring.actions
    
    
[36m[2023-04-09 23:09:33 DEBUG] [cli:601][39m Failed to discover chaosspring.actions
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 36, in discover
        install(package_name)
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 42, in install
        raise DiscoveryFailed(msg)
    chaoslib.exceptions.DiscoveryFailed: failed to install `chaosspring.actions`
[31m[2023-04-09 23:09:33 CRITICAL] [cli:602][39m failed to install `chaosspring.actions`
[36m[2023-04-09 23:09:38 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:09:38 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:09:38 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:09:39 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:09:39 INFO] [package:22][39m Attempting to download and install package 'chaosspring'
[36m[2023-04-09 23:09:40 DEBUG] [package:32][39m 
[36m[2023-04-09 23:09:40 DEBUG] [package:36][39m failed to install `chaosspring`
    =================
    
    =================
    ERROR: Could not find a version that satisfies the requirement chaosspring (from versions: none)
    ERROR: No matching distribution found for chaosspring
    
    
[36m[2023-04-09 23:09:40 DEBUG] [cli:601][39m Failed to discover chaosspring
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 36, in discover
        install(package_name)
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 42, in install
        raise DiscoveryFailed(msg)
    chaoslib.exceptions.DiscoveryFailed: failed to install `chaosspring`
[31m[2023-04-09 23:09:40 CRITICAL] [cli:602][39m failed to install `chaosspring`
[36m[2023-04-09 23:10:19 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:10:19 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:10:19 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:10:20 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:10:20 INFO] [package:22][39m Attempting to download and install package 'chaostoolkit-spring'
[36m[2023-04-09 23:10:22 DEBUG] [package:32][39m Requirement already satisfied: chaostoolkit-spring in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (0.3.2)
    Requirement already satisfied: chaostoolkit-lib>=0.15.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-spring) (1.34.1)
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-spring) (1.7.0)
    Requirement already satisfied: requests~=2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (2.28.2)
    Requirement already satisfied: pyyaml~=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (6.0)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (6.2.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero->chaostoolkit-spring) (0.4.6)
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (3.15.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (3.4)
    Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (1.26.15)
    Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.15.0->chaostoolkit-spring) (2022.12.7)
    
[32m[2023-04-09 23:10:22 INFO] [package:44][39m Package downloaded and installed in current environment
[36m[2023-04-09 23:10:22 DEBUG] [cli:601][39m Failed to discover chaostoolkit-spring
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 38, in discover
        discover_func = get_discover_function(package)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 69, in get_discover_function
        raise DiscoveryFailed(
    chaoslib.exceptions.DiscoveryFailed: package 'chaosspring' does not export a `discover` function
[31m[2023-04-09 23:10:22 CRITICAL] [cli:602][39m package 'chaosspring' does not export a `discover` function
[36m[2023-04-09 23:22:05 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:22:06 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:22:06 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:22:07 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:22:07 INFO] [package:22][39m Attempting to download and install package 'chaostoolkit-prometheus'
[36m[2023-04-09 23:22:21 DEBUG] [package:32][39m Collecting chaostoolkit-prometheus
      Downloading chaostoolkit_prometheus-0.5.0-py2.py3-none-any.whl (11 kB)
    Requirement already satisfied: chaostoolkit-lib~=1.27 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-prometheus) (1.34.1)
    Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-prometheus) (2.28.2)
    Collecting dateparser
      Downloading dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
         -------------------------------------- 293.8/293.8 kB 2.3 MB/s eta 0:00:00
    Collecting maya
      Downloading maya-0.6.1-py2.py3-none-any.whl (12 kB)
    Collecting prometheus-client
      Downloading prometheus_client-0.16.0-py3-none-any.whl (122 kB)
         -------------------------------------- 122.5/122.5 kB 7.0 MB/s eta 0:00:00
    Requirement already satisfied: logzero~=1.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (1.7.0)
    Requirement already satisfied: pyyaml~=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (6.0)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (6.2.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (3.4)
    Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (1.26.15)
    Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (2022.12.7)
    Collecting python-dateutil
      Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
         -------------------------------------- 247.7/247.7 kB 5.1 MB/s eta 0:00:00
    Collecting pytz
      Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
         -------------------------------------- 502.3/502.3 kB 4.5 MB/s eta 0:00:00
    Collecting regex!=2019.02.19,!=2021.8.27
      Downloading regex-2023.3.23.tar.gz (391 kB)
         -------------------------------------- 392.0/392.0 kB 2.7 MB/s eta 0:00:00
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Downloading tzlocal-4.3-py3-none-any.whl (20 kB)
    Collecting humanize
      Downloading humanize-4.6.0-py3-none-any.whl (109 kB)
         -------------------------------------- 110.0/110.0 kB 3.1 MB/s eta 0:00:00
    Collecting pendulum>=2.0.2
      Downloading pendulum-2.1.2.tar.gz (81 kB)
         ---------------------------------------- 81.2/81.2 kB 2.2 MB/s eta 0:00:00
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting snaptime
      Downloading snaptime-0.2.4.tar.gz (2.9 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (3.15.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero~=1.5->chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (0.4.6)
    Collecting pytzdata>=2020.1
      Downloading pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
         -------------------------------------- 490.0/490.0 kB 4.4 MB/s eta 0:00:00
    Collecting six>=1.5
      Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
    Collecting pytz-deprecation-shim
      Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Collecting tzdata
      Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
         -------------------------------------- 341.8/341.8 kB 5.3 MB/s eta 0:00:00
    Building wheels for collected packages: pendulum
      Building wheel for pendulum (pyproject.toml): started
      Building wheel for pendulum (pyproject.toml): finished with status 'error'
    Failed to build pendulum
    
[36m[2023-04-09 23:22:21 DEBUG] [package:36][39m failed to install `chaostoolkit-prometheus`
    =================
    Collecting chaostoolkit-prometheus
      Downloading chaostoolkit_prometheus-0.5.0-py2.py3-none-any.whl (11 kB)
    Requirement already satisfied: chaostoolkit-lib~=1.27 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-prometheus) (1.34.1)
    Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-prometheus) (2.28.2)
    Collecting dateparser
      Downloading dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
         -------------------------------------- 293.8/293.8 kB 2.3 MB/s eta 0:00:00
    Collecting maya
      Downloading maya-0.6.1-py2.py3-none-any.whl (12 kB)
    Collecting prometheus-client
      Downloading prometheus_client-0.16.0-py3-none-any.whl (122 kB)
         -------------------------------------- 122.5/122.5 kB 7.0 MB/s eta 0:00:00
    Requirement already satisfied: logzero~=1.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (1.7.0)
    Requirement already satisfied: pyyaml~=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (6.0)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (6.2.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (3.4)
    Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (1.26.15)
    Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests->chaostoolkit-prometheus) (2022.12.7)
    Collecting python-dateutil
      Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
         -------------------------------------- 247.7/247.7 kB 5.1 MB/s eta 0:00:00
    Collecting pytz
      Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
         -------------------------------------- 502.3/502.3 kB 4.5 MB/s eta 0:00:00
    Collecting regex!=2019.02.19,!=2021.8.27
      Downloading regex-2023.3.23.tar.gz (391 kB)
         -------------------------------------- 392.0/392.0 kB 2.7 MB/s eta 0:00:00
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Downloading tzlocal-4.3-py3-none-any.whl (20 kB)
    Collecting humanize
      Downloading humanize-4.6.0-py3-none-any.whl (109 kB)
         -------------------------------------- 110.0/110.0 kB 3.1 MB/s eta 0:00:00
    Collecting pendulum>=2.0.2
      Downloading pendulum-2.1.2.tar.gz (81 kB)
         ---------------------------------------- 81.2/81.2 kB 2.2 MB/s eta 0:00:00
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting snaptime
      Downloading snaptime-0.2.4.tar.gz (2.9 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (3.15.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero~=1.5->chaostoolkit-lib~=1.27->chaostoolkit-prometheus) (0.4.6)
    Collecting pytzdata>=2020.1
      Downloading pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
         -------------------------------------- 490.0/490.0 kB 4.4 MB/s eta 0:00:00
    Collecting six>=1.5
      Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
    Collecting pytz-deprecation-shim
      Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Collecting tzdata
      Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
         -------------------------------------- 341.8/341.8 kB 5.3 MB/s eta 0:00:00
    Building wheels for collected packages: pendulum
      Building wheel for pendulum (pyproject.toml): started
      Building wheel for pendulum (pyproject.toml): finished with status 'error'
    Failed to build pendulum
    
    =================
      error: subprocess-exited-with-error
      
      Building wheel for pendulum (pyproject.toml) did not run successfully.
      exit code: 1
      
      [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Temp\pip-install-nvnyilzv\pendulum_a122a6728244462199e8028d34abe885\build.py", line 5, in <module>
          from distutils.command.build_ext import build_ext
      ModuleNotFoundError: No module named 'distutils'
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8r006yes\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 56, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8r006yes\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 85, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8r006yes\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 120, in build
          self._build(zip_file)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8r006yes\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 169, in _build
          self._run_build_script(self._package.build_script)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8r006yes\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 229, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:/Users/User/AppData/Local/Programs/Python/Python312/python.exe', 'build.py']' returned non-zero exit status 1.
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for pendulum
    ERROR: Could not build wheels for pendulum, which is required to install pyproject.toml-based projects
    
    
[36m[2023-04-09 23:22:21 DEBUG] [cli:601][39m Failed to discover chaostoolkit-prometheus
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 36, in discover
        install(package_name)
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 42, in install
        raise DiscoveryFailed(msg)
    chaoslib.exceptions.DiscoveryFailed: failed to install `chaostoolkit-prometheus`
[31m[2023-04-09 23:22:21 CRITICAL] [cli:602][39m failed to install `chaostoolkit-prometheus`
[36m[2023-04-09 23:25:29 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:25:29 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:25:29 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:25:30 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:25:30 INFO] [package:22][39m Attempting to download and install package 'chaostoolkit-ansible'
[36m[2023-04-09 23:25:59 DEBUG] [package:32][39m Collecting chaostoolkit-ansible
      Downloading chaostoolkit_ansible-0.2.3-py3-none-any.whl (11 kB)
    Requirement already satisfied: chaostoolkit>=1.7.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-ansible) (1.15.1)
    Requirement already satisfied: chaostoolkit-lib>=1.1.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-ansible) (1.34.1)
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-ansible) (1.7.0)
    Collecting ansible<3.0,>=2.9.0
      Downloading ansible-2.10.7.tar.gz (29.9 MB)
         ---------------------------------------- 29.9/29.9 MB 5.6 MB/s eta 0:00:00
    
[36m[2023-04-09 23:25:59 DEBUG] [package:36][39m failed to install `chaostoolkit-ansible`
    =================
    Collecting chaostoolkit-ansible
      Downloading chaostoolkit_ansible-0.2.3-py3-none-any.whl (11 kB)
    Requirement already satisfied: chaostoolkit>=1.7.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-ansible) (1.15.1)
    Requirement already satisfied: chaostoolkit-lib>=1.1.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-ansible) (1.34.1)
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-ansible) (1.7.0)
    Collecting ansible<3.0,>=2.9.0
      Downloading ansible-2.10.7.tar.gz (29.9 MB)
         ---------------------------------------- 29.9/29.9 MB 5.6 MB/s eta 0:00:00
    
    =================
    ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-7m0pvsop\\ansible_3f5d04bf7ddc4c3bb0ee1315ec318081\\ansible_collections/community/aws/tests/unit/modules/placebo_recordings/aws_direct_connect_connection/associations_are_not_updated/directconnect.DescribeConnections_1.json'
    HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths
    
    
    
[36m[2023-04-09 23:25:59 DEBUG] [cli:601][39m Failed to discover chaostoolkit-ansible
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 36, in discover
        install(package_name)
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 42, in install
        raise DiscoveryFailed(msg)
    chaoslib.exceptions.DiscoveryFailed: failed to install `chaostoolkit-ansible`
[31m[2023-04-09 23:25:59 CRITICAL] [cli:602][39m failed to install `chaostoolkit-ansible`
[36m[2023-04-09 23:26:47 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:26:47 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:26:47 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:26:48 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:26:48 INFO] [package:22][39m Attempting to download and install package 'chaostoolkit-kubernetes'
[36m[2023-04-09 23:27:14 DEBUG] [package:32][39m Collecting chaostoolkit-kubernetes
      Downloading chaostoolkit_kubernetes-0.26.4-py3-none-any.whl (32 kB)
    Collecting dateparser
      Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
    Collecting kubernetes
      Downloading kubernetes-26.1.0-py2.py3-none-any.whl (1.4 MB)
         ---------------------------------------- 1.4/1.4 MB 2.6 MB/s eta 0:00:00
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.7.0)
    Requirement already satisfied: chaostoolkit-lib>=0.20.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.34.1)
    Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (6.0)
    Requirement already satisfied: requests~=2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (2.28.2)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (6.2.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero->chaostoolkit-kubernetes) (0.4.6)
    Collecting python-dateutil
      Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    Collecting pytz
      Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
    Collecting regex!=2019.02.19,!=2021.8.27
      Using cached regex-2023.3.23.tar.gz (391 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
    Requirement already satisfied: certifi>=14.05.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (2022.12.7)
    Collecting six>=1.9.0
      Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
    Requirement already satisfied: setuptools>=21.0.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (65.5.0)
    Collecting google-auth>=1.0.1
      Downloading google_auth-2.17.2-py2.py3-none-any.whl (178 kB)
         -------------------------------------- 178.2/178.2 kB 3.6 MB/s eta 0:00:00
    Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0
      Downloading websocket_client-1.5.1-py3-none-any.whl (55 kB)
         ---------------------------------------- 55.9/55.9 kB 2.9 MB/s eta 0:00:00
    Collecting requests-oauthlib
      Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: urllib3>=1.24.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.26.15)
    Collecting cachetools<6.0,>=2.0.0
      Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
    Collecting pyasn1-modules>=0.2.1
      Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
         -------------------------------------- 155.3/155.3 kB 4.7 MB/s eta 0:00:00
    Collecting rsa<5,>=3.1.4
      Downloading rsa-4.9-py3-none-any.whl (34 kB)
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.15.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.4)
    Collecting oauthlib>=3.0.0
      Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
         -------------------------------------- 151.7/151.7 kB 4.6 MB/s eta 0:00:00
    Collecting pytz-deprecation-shim
      Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Collecting tzdata
      Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
    Collecting pyasn1<0.5.0,>=0.4.6
      Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
         -------------------------------------- 77.1/77.1 kB 357.8 kB/s eta 0:00:00
    Installing collected packages: pytz, pyasn1, websocket-client, tzdata, six, rsa, regex, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, pytz-deprecation-shim, python-dateutil, google-auth, tzlocal, kubernetes, dateparser, chaostoolkit-kubernetes
      Running setup.py install for regex: started
      Running setup.py install for regex: finished with status 'error'
    
[36m[2023-04-09 23:27:14 DEBUG] [package:36][39m failed to install `chaostoolkit-kubernetes`
    =================
    Collecting chaostoolkit-kubernetes
      Downloading chaostoolkit_kubernetes-0.26.4-py3-none-any.whl (32 kB)
    Collecting dateparser
      Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
    Collecting kubernetes
      Downloading kubernetes-26.1.0-py2.py3-none-any.whl (1.4 MB)
         ---------------------------------------- 1.4/1.4 MB 2.6 MB/s eta 0:00:00
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.7.0)
    Requirement already satisfied: chaostoolkit-lib>=0.20.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.34.1)
    Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (6.0)
    Requirement already satisfied: requests~=2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (2.28.2)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (6.2.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero->chaostoolkit-kubernetes) (0.4.6)
    Collecting python-dateutil
      Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    Collecting pytz
      Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
    Collecting regex!=2019.02.19,!=2021.8.27
      Using cached regex-2023.3.23.tar.gz (391 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
    Requirement already satisfied: certifi>=14.05.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (2022.12.7)
    Collecting six>=1.9.0
      Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
    Requirement already satisfied: setuptools>=21.0.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (65.5.0)
    Collecting google-auth>=1.0.1
      Downloading google_auth-2.17.2-py2.py3-none-any.whl (178 kB)
         -------------------------------------- 178.2/178.2 kB 3.6 MB/s eta 0:00:00
    Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0
      Downloading websocket_client-1.5.1-py3-none-any.whl (55 kB)
         ---------------------------------------- 55.9/55.9 kB 2.9 MB/s eta 0:00:00
    Collecting requests-oauthlib
      Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: urllib3>=1.24.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.26.15)
    Collecting cachetools<6.0,>=2.0.0
      Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
    Collecting pyasn1-modules>=0.2.1
      Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
         -------------------------------------- 155.3/155.3 kB 4.7 MB/s eta 0:00:00
    Collecting rsa<5,>=3.1.4
      Downloading rsa-4.9-py3-none-any.whl (34 kB)
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.15.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.4)
    Collecting oauthlib>=3.0.0
      Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
         -------------------------------------- 151.7/151.7 kB 4.6 MB/s eta 0:00:00
    Collecting pytz-deprecation-shim
      Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Collecting tzdata
      Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
    Collecting pyasn1<0.5.0,>=0.4.6
      Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
         -------------------------------------- 77.1/77.1 kB 357.8 kB/s eta 0:00:00
    Installing collected packages: pytz, pyasn1, websocket-client, tzdata, six, rsa, regex, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, pytz-deprecation-shim, python-dateutil, google-auth, tzlocal, kubernetes, dateparser, chaostoolkit-kubernetes
      Running setup.py install for regex: started
      Running setup.py install for regex: finished with status 'error'
    
    =================
      DEPRECATION: regex is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
      error: subprocess-exited-with-error
      
      Running setup.py install for regex did not run successfully.
      exit code: 1
      
      [15 lines of output]
      running install
      C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\regex
      copying regex_3\__init__.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\regex.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\_regex_core.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\test_regex.py -> build\lib.win-amd64-cpython-312\regex
      running build_ext
      building 'regex._regex' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    Encountered error while trying to install package.
    
    regex
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
    
    
[36m[2023-04-09 23:27:14 DEBUG] [cli:601][39m Failed to discover chaostoolkit-kubernetes
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 36, in discover
        install(package_name)
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 42, in install
        raise DiscoveryFailed(msg)
    chaoslib.exceptions.DiscoveryFailed: failed to install `chaostoolkit-kubernetes`
[31m[2023-04-09 23:27:14 CRITICAL] [cli:602][39m failed to install `chaostoolkit-kubernetes`
[36m[2023-04-09 23:27:41 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:27:41 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:27:41 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:27:42 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:27:42 INFO] [package:22][39m Attempting to download and install package 'chaostoolkit-kubernetes'
[36m[2023-04-09 23:27:48 DEBUG] [package:32][39m Collecting chaostoolkit-kubernetes
      Using cached chaostoolkit_kubernetes-0.26.4-py3-none-any.whl (32 kB)
    Collecting dateparser
      Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
    Collecting kubernetes
      Using cached kubernetes-26.1.0-py2.py3-none-any.whl (1.4 MB)
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.7.0)
    Requirement already satisfied: chaostoolkit-lib>=0.20.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.34.1)
    Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (6.0)
    Requirement already satisfied: requests~=2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (2.28.2)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (6.2.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero->chaostoolkit-kubernetes) (0.4.6)
    Collecting python-dateutil
      Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    Requirement already satisfied: pytz in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from dateparser->chaostoolkit-kubernetes) (2023.3)
    Collecting regex!=2019.02.19,!=2021.8.27
      Using cached regex-2023.3.23.tar.gz (391 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
    Requirement already satisfied: certifi>=14.05.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (2022.12.7)
    Requirement already satisfied: six>=1.9.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.16.0)
    Requirement already satisfied: setuptools>=21.0.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (65.5.0)
    Collecting google-auth>=1.0.1
      Using cached google_auth-2.17.2-py2.py3-none-any.whl (178 kB)
    Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.5.1)
    Collecting requests-oauthlib
      Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: urllib3>=1.24.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.26.15)
    Collecting cachetools<6.0,>=2.0.0
      Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
    Collecting pyasn1-modules>=0.2.1
      Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
    Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (4.9)
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.15.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.4)
    Collecting oauthlib>=3.0.0
      Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
    Collecting pytz-deprecation-shim
      Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Requirement already satisfied: tzdata in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from tzlocal->dateparser->chaostoolkit-kubernetes) (2023.3)
    Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (0.4.8)
    Installing collected packages: regex, pytz-deprecation-shim, python-dateutil, pyasn1-modules, oauthlib, cachetools, tzlocal, requests-oauthlib, google-auth, kubernetes, dateparser, chaostoolkit-kubernetes
      Running setup.py install for regex: started
      Running setup.py install for regex: finished with status 'error'
    
[36m[2023-04-09 23:27:48 DEBUG] [package:36][39m failed to install `chaostoolkit-kubernetes`
    =================
    Collecting chaostoolkit-kubernetes
      Using cached chaostoolkit_kubernetes-0.26.4-py3-none-any.whl (32 kB)
    Collecting dateparser
      Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
    Collecting kubernetes
      Using cached kubernetes-26.1.0-py2.py3-none-any.whl (1.4 MB)
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.7.0)
    Requirement already satisfied: chaostoolkit-lib>=0.20.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.34.1)
    Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (6.0)
    Requirement already satisfied: requests~=2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (2.28.2)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (6.2.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero->chaostoolkit-kubernetes) (0.4.6)
    Collecting python-dateutil
      Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    Requirement already satisfied: pytz in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from dateparser->chaostoolkit-kubernetes) (2023.3)
    Collecting regex!=2019.02.19,!=2021.8.27
      Using cached regex-2023.3.23.tar.gz (391 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
    Requirement already satisfied: certifi>=14.05.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (2022.12.7)
    Requirement already satisfied: six>=1.9.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.16.0)
    Requirement already satisfied: setuptools>=21.0.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (65.5.0)
    Collecting google-auth>=1.0.1
      Using cached google_auth-2.17.2-py2.py3-none-any.whl (178 kB)
    Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.5.1)
    Collecting requests-oauthlib
      Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: urllib3>=1.24.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.26.15)
    Collecting cachetools<6.0,>=2.0.0
      Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
    Collecting pyasn1-modules>=0.2.1
      Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
    Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (4.9)
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.15.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.4)
    Collecting oauthlib>=3.0.0
      Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
    Collecting pytz-deprecation-shim
      Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Requirement already satisfied: tzdata in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from tzlocal->dateparser->chaostoolkit-kubernetes) (2023.3)
    Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (0.4.8)
    Installing collected packages: regex, pytz-deprecation-shim, python-dateutil, pyasn1-modules, oauthlib, cachetools, tzlocal, requests-oauthlib, google-auth, kubernetes, dateparser, chaostoolkit-kubernetes
      Running setup.py install for regex: started
      Running setup.py install for regex: finished with status 'error'
    
    =================
      DEPRECATION: regex is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
      error: subprocess-exited-with-error
      
      Running setup.py install for regex did not run successfully.
      exit code: 1
      
      [15 lines of output]
      running install
      C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\regex
      copying regex_3\__init__.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\regex.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\_regex_core.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\test_regex.py -> build\lib.win-amd64-cpython-312\regex
      running build_ext
      building 'regex._regex' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    Encountered error while trying to install package.
    
    regex
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
    
    
[36m[2023-04-09 23:27:48 DEBUG] [cli:601][39m Failed to discover chaostoolkit-kubernetes
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 36, in discover
        install(package_name)
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 42, in install
        raise DiscoveryFailed(msg)
    chaoslib.exceptions.DiscoveryFailed: failed to install `chaostoolkit-kubernetes`
[31m[2023-04-09 23:27:48 CRITICAL] [cli:602][39m failed to install `chaostoolkit-kubernetes`
[36m[2023-04-09 23:29:25 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-04-09 23:29:25 DEBUG] [cli:115][39m Running command 'discover'
[36m[2023-04-09 23:29:25 DEBUG] [cli:119][39m Using settings file 'C:\Users\User\.chaostoolkit\settings.yaml'
[36m[2023-04-09 23:29:26 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\User\.chaostoolkit\settings.yaml'.
[32m[2023-04-09 23:29:26 INFO] [package:22][39m Attempting to download and install package 'chaostoolkit-kubernetes'
[36m[2023-04-09 23:29:31 DEBUG] [package:32][39m Collecting chaostoolkit-kubernetes
      Using cached chaostoolkit_kubernetes-0.26.4-py3-none-any.whl (32 kB)
    Collecting dateparser
      Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
    Collecting kubernetes
      Using cached kubernetes-26.1.0-py2.py3-none-any.whl (1.4 MB)
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.7.0)
    Requirement already satisfied: chaostoolkit-lib>=0.20.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.34.1)
    Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (6.0)
    Requirement already satisfied: requests~=2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (2.28.2)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (6.2.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero->chaostoolkit-kubernetes) (0.4.6)
    Collecting python-dateutil
      Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    Requirement already satisfied: pytz in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from dateparser->chaostoolkit-kubernetes) (2023.3)
    Collecting regex!=2019.02.19,!=2021.8.27
      Using cached regex-2023.3.23.tar.gz (391 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
    Requirement already satisfied: certifi>=14.05.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (2022.12.7)
    Requirement already satisfied: six>=1.9.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.16.0)
    Requirement already satisfied: setuptools>=21.0.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (65.5.0)
    Collecting google-auth>=1.0.1
      Using cached google_auth-2.17.2-py2.py3-none-any.whl (178 kB)
    Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.5.1)
    Collecting requests-oauthlib
      Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: urllib3>=1.24.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.26.15)
    Collecting cachetools<6.0,>=2.0.0
      Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
    Collecting pyasn1-modules>=0.2.1
      Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
    Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (4.9)
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.15.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.4)
    Collecting oauthlib>=3.0.0
      Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
    Collecting pytz-deprecation-shim
      Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Requirement already satisfied: tzdata in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from tzlocal->dateparser->chaostoolkit-kubernetes) (2023.3)
    Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (0.4.8)
    Installing collected packages: regex, pytz-deprecation-shim, python-dateutil, pyasn1-modules, oauthlib, cachetools, tzlocal, requests-oauthlib, google-auth, kubernetes, dateparser, chaostoolkit-kubernetes
      Running setup.py install for regex: started
      Running setup.py install for regex: finished with status 'error'
    
[36m[2023-04-09 23:29:31 DEBUG] [package:36][39m failed to install `chaostoolkit-kubernetes`
    =================
    Collecting chaostoolkit-kubernetes
      Using cached chaostoolkit_kubernetes-0.26.4-py3-none-any.whl (32 kB)
    Collecting dateparser
      Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
    Collecting kubernetes
      Using cached kubernetes-26.1.0-py2.py3-none-any.whl (1.4 MB)
    Requirement already satisfied: logzero in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.7.0)
    Requirement already satisfied: chaostoolkit-lib>=0.20.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (1.34.1)
    Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-kubernetes) (6.0)
    Requirement already satisfied: requests~=2.21 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (2.28.2)
    Requirement already satisfied: importlib-metadata>=6.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (6.2.0)
    Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from logzero->chaostoolkit-kubernetes) (0.4.6)
    Collecting python-dateutil
      Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    Requirement already satisfied: pytz in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from dateparser->chaostoolkit-kubernetes) (2023.3)
    Collecting regex!=2019.02.19,!=2021.8.27
      Using cached regex-2023.3.23.tar.gz (391 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting tzlocal
      Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
    Requirement already satisfied: certifi>=14.05.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (2022.12.7)
    Requirement already satisfied: six>=1.9.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.16.0)
    Requirement already satisfied: setuptools>=21.0.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (65.5.0)
    Collecting google-auth>=1.0.1
      Using cached google_auth-2.17.2-py2.py3-none-any.whl (178 kB)
    Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.5.1)
    Collecting requests-oauthlib
      Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: urllib3>=1.24.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from kubernetes->chaostoolkit-kubernetes) (1.26.15)
    Collecting cachetools<6.0,>=2.0.0
      Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
    Collecting pyasn1-modules>=0.2.1
      Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
    Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (4.9)
    Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata>=6.0->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.15.0)
    Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.1.0)
    Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from requests~=2.21->chaostoolkit-lib>=0.20.0->chaostoolkit-kubernetes) (3.4)
    Collecting oauthlib>=3.0.0
      Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
    Collecting pytz-deprecation-shim
      Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
    Requirement already satisfied: tzdata in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from tzlocal->dateparser->chaostoolkit-kubernetes) (2023.3)
    Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes->chaostoolkit-kubernetes) (0.4.8)
    Installing collected packages: regex, pytz-deprecation-shim, python-dateutil, pyasn1-modules, oauthlib, cachetools, tzlocal, requests-oauthlib, google-auth, kubernetes, dateparser, chaostoolkit-kubernetes
      Running setup.py install for regex: started
      Running setup.py install for regex: finished with status 'error'
    
    =================
      DEPRECATION: regex is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
      error: subprocess-exited-with-error
      
      Running setup.py install for regex did not run successfully.
      exit code: 1
      
      [15 lines of output]
      running install
      C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\regex
      copying regex_3\__init__.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\regex.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\_regex_core.py -> build\lib.win-amd64-cpython-312\regex
      copying regex_3\test_regex.py -> build\lib.win-amd64-cpython-312\regex
      running build_ext
      building 'regex._regex' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    Encountered error while trying to install package.
    
    regex
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
    
    
[36m[2023-04-09 23:29:31 DEBUG] [cli:601][39m Failed to discover chaostoolkit-kubernetes
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaostoolkit\cli.py", line 594, in discover
        discovery = disco(
                    ^^^^^^
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\discover.py", line 36, in discover
        install(package_name)
      File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\chaoslib\discovery\package.py", line 42, in install
        raise DiscoveryFailed(msg)
    chaoslib.exceptions.DiscoveryFailed: failed to install `chaostoolkit-kubernetes`
[31m[2023-04-09 23:29:31 CRITICAL] [cli:602][39m failed to install `chaostoolkit-kubernetes`
